### ISSUE TITLE
Internal Compiler Error on jar library 

### ISSUE THREAD

**Issue by zejtin** [ikvm-revived/ikvm#142] opened 2022-09-08 14:55 UTC
Hello, I am trying to convert a jar library to dll. This is my command:
`ikvmc.exe -target:library JWitsml.jar`

This is the error I get

```
IKVM.NET Compiler (8.2.1+Branch.main.Sha.e85684966cf595d7942d6930fda9c27d23b509e1)
Copyright c 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug


*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

ikvmc, Version=8.2.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Users\600008\Downloads\IKVM-8.2.1-tools-ikvmc-netcoreapp3.1\win7-x64\
3.1.27 64-bit

System.IO.FileNotFoundException: netstandard
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\src\IKVM.Reflection\Universe.cs:line 789
   at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in D:\a\ikvm\ikvm\src\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
   at ikvmc.IkvmcCompiler.Compile(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 178
   at ikvmc.IkvmcCompiler.Main(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 112
```

I have also tried running: `ikvmc.exe JWitsml.jar` and tried with explicit path

**Comment by NightOwl888** [comment] 2022-09-08 17:15
This is a duplicate of #74. 

However, we recommend using [`<IkvmReference>`](https://github.com/ikvm-revived/ikvm#ikvmreference) for private/local `.jar` files and [`<MavenReference`>](https://github.com/ikvm-revived/ikvm-maven#readme) public `.jar` files that are on Maven.  `ikvmc` should only be used for advanced scenarios where these options don't meet your needs.

**Closed by NightOwl888** 2022-09-08 17:15 UTC
